import React, { useState } from 'react'
import { Sparkles } from 'lucide-react'
import { Card } from '@/components/common'
import { generateAgentBriefing } from '@/services/applications'
import type { AgentBriefing } from '@/services/applications'

interface AgentBriefingPanelProps {
  applicationId: string
  /** Briefing persisted from an earlier run (read from _decision_meta), if any. */
  initialBriefing?: AgentBriefing | null
}

/**
 * Reviewer briefing generated by the underwriting agent (Claude).
 *
 * Advisory only, and the UI says so: the agent never recommends a verdict, and
 * the reviewer's decision flow (ReviewerFeedbackForm) is untouched by it. When
 * the backend has no ANTHROPIC_API_KEY the button degrades to the 503 message.
 */
export const AgentBriefingPanel: React.FC<AgentBriefingPanelProps> = ({
  applicationId,
  initialBriefing = null,
}) => {
  const [briefing, setBriefing] = useState<AgentBriefing | null>(initialBriefing)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleGenerate = async () => {
    setIsLoading(true)
    setError(null)
    try {
      setBriefing(await generateAgentBriefing(applicationId))
    } catch (generateError) {
      setError(
        generateError instanceof Error ? generateError.message : 'The agent is unavailable.',
      )
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Card
      title="Agent Briefing"
      description="AI-generated case briefing for the reviewer — advisory only, never a verdict."
    >
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={() => void handleGenerate()}
            disabled={isLoading}
            className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-700 disabled:opacity-50"
          >
            <Sparkles className="h-4 w-4" />
            {isLoading ? 'Analysing the case…' : briefing ? 'Regenerate briefing' : 'Generate briefing'}
          </button>
          {briefing?.generatedAt && (
            <span className="text-xs text-neutral-500">
              {briefing.model ?? 'Claude'} · {new Date(briefing.generatedAt).toLocaleString()}
            </span>
          )}
        </div>

        {error && (
          <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
            {error}
          </p>
        )}

        {briefing && (
          <div className="space-y-4 text-sm">
            <p className="text-neutral-800">{briefing.summary}</p>

            <div className="grid gap-4 md:grid-cols-2">
              <BriefingList title="Risk factors" items={briefing.riskFactors} tone="red" />
              <BriefingList title="Mitigants" items={briefing.mitigants} tone="green" />
              <BriefingList title="Data quality flags" items={briefing.dataQualityFlags} tone="amber" />
              <BriefingList title="Suggested checks" items={briefing.suggestedChecks} tone="blue" />
            </div>

            {briefing.suggestedReasonCodes.length > 0 && (
              <div>
                <p className="mb-1 font-semibold text-neutral-900">Reason codes the evidence could support</p>
                <div className="flex flex-wrap gap-2">
                  {briefing.suggestedReasonCodes.map((code) => (
                    <span
                      key={code}
                      className="rounded-full border border-neutral-300 bg-neutral-50 px-2.5 py-0.5 font-mono text-xs text-neutral-700"
                    >
                      {code}
                    </span>
                  ))}
                </div>
              </div>
            )}

            <p className="text-xs text-neutral-500">
              Generated by an AI assistant from the decision report. It does not decide anything —
              verify its flags against the file before relying on them.
            </p>
          </div>
        )}
      </div>
    </Card>
  )
}

const LIST_TONES: Record<string, string> = {
  red: 'text-red-700',
  green: 'text-green-700',
  amber: 'text-amber-700',
  blue: 'text-blue-700',
}

const BriefingList: React.FC<{ title: string; items: string[]; tone: string }> = ({
  title,
  items,
  tone,
}) => (
  <div>
    <p className={`mb-1 font-semibold ${LIST_TONES[tone] ?? 'text-neutral-900'}`}>{title}</p>
    {items.length === 0 ? (
      <p className="text-xs text-neutral-400">None identified.</p>
    ) : (
      <ul className="list-disc space-y-1 pl-5 text-neutral-700">
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    )}
  </div>
)
