"""Add the best FE-v2 model to the dashboard leaderboard, clearly labelled.

Reads the out-of-fold predictions written by features_vs_fusion.py, picks the
best v2 model, computes the same operating-point metrics every other
leaderboard row uses (own Youden threshold, approval framing), and writes one
row named '<Model> (FE-v2)' so nobody can mistake it for the v1-feature rows.

Committed because artifacts are regenerated by scripts, never hand-edited.

Run:  python -m research.analysis.add_v2_leaderboard_row
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, brier_score_loss, roc_auc_score

from research.analysis.score_tabfm import _operating_metrics

REPO = Path(__file__).resolve().parents[2]
OOF_CSV = REPO / "reports" / "v2_oof_predictions.csv"
RESULTS = REPO / "reports" / "features_vs_fusion.json"
METRICS_CSV = REPO / "backend" / "artifacts" / "model_metrics.csv"


def main() -> None:
    results = json.loads(RESULTS.read_text())
    best = max(results["models"], key=lambda m: results["models"][m]["v2"]["oof_auc"])
    fold_aucs = results["models"][best]["v2"]["fold_aucs"]
    label = f"{best} (FE-v2)"

    oof = pd.read_csv(OOF_CSV)
    y = oof["y_target"].astype(int).to_numpy()
    p_default = oof[f"pd_{best}"].to_numpy()

    operating = _operating_metrics(y, 1.0 - p_default)
    row = {
        "model": label,
        "roc_auc": round(float(roc_auc_score(y, p_default)), 4),
        "std_auc": round(float(np.std(fold_aucs)), 5),
        "recall": operating["recall"],
        "custom_score": round(float(roc_auc_score(y, p_default)), 4),
        "accuracy": operating["accuracy"],
        "precision": operating["precision"],
        "f1": operating["f1"],
        "auc": round(float(roc_auc_score(y, p_default)), 4),
        "pr_auc_default": round(float(average_precision_score(y, p_default)), 4),
        "brier": round(float(brier_score_loss(y, p_default)), 5),
        "operating_threshold": operating["operating_threshold"],
        "default_capture": operating["default_capture"],
        "approve_rate": operating["approve_rate"],
    }

    table = pd.read_csv(METRICS_CSV)
    table = table[table["model"] != label]
    table = pd.concat([table, pd.DataFrame([row])], ignore_index=True)
    table.to_csv(METRICS_CSV, index=False)
    print(f"[leaderboard] wrote row {label!r}: AUC {row['roc_auc']} "
          f"({len(y):,}-row OOF, engineered features) to {METRICS_CSV}")


if __name__ == "__main__":
    main()
