import type { DashboardMetrics, PublicMetrics, TrendDataPoint } from '@/types/api'
import type { LoanApplication } from '@/types/application'

export const publicMetrics: PublicMetrics = {
  applicationsProcessed: 1250,
  approvalSpeedup: 2.3,
  accuracy: 94.2,
  automationRate: 78,
}

export const dashboardMetrics: DashboardMetrics = {
  totalApplications: 1250,
  approved: 850,
  rejected: 200,
  deferred: 200,
  averageProcessingTime: 120,
  approvalRate: 68,
  avgLoanAmount: 620000,
  automationRate: 82,
}

export const trendData: TrendDataPoint[] = [
  { date: 'Week 1', count: 120, approved: 78, rejected: 24, deferred: 18 },
  { date: 'Week 2', count: 145, approved: 98, rejected: 26, deferred: 21 },
  { date: 'Week 3', count: 160, approved: 108, rejected: 29, deferred: 23 },
  { date: 'Week 4', count: 210, approved: 144, rejected: 34, deferred: 32 },
]

export const mockApplications: LoanApplication[] = [
  {
    id: 'app-uuid-123',
    createdAt: '2025-04-20T10:30:00Z',
    updatedAt: '2025-04-20T10:45:00Z',
    status: 'deferred',
    source: 'seed',
    applicantId: 'cust-001',
    applicantName: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    phone: '+91 9876543210',
    loanAmount: 500000,
    loanPurpose: 'business',
    loanTenure: 60,
    applicationData: {
      firstName: 'Rajesh',
      lastName: 'Kumar',
      gender: 'male',
      education: 'graduate',
      monthlyIncome: 50000,
      annualIncome: 600000,
      emi: 8000,
      existingEmis: 8000,
      employmentType: 'self-employed',
      yearsOfEmployment: 6,
      assets: 1000000,
      residentialAssetsValue: 650000,
      commercialAssetsValue: 120000,
      bankBalance: 230000,
      totalAssets: 1000000,
      liabilities: 150000,
      creditScore: 650,
      creditHistory: 'average',
      totalLoans: 4,
      activeLoans: 2,
      closedLoans: 2,
      missedPayments: 1,
      creditUtilizationRatio: 41,
      emiIncomeRatio: 16,
      loanIncomeRatio: 83,
      debtToIncomeRatio: 30,
      age: 35,
      dependents: 2,
      maritalStatus: 'married',
      residenceType: 'owned',
      region: 'west',
      city: 'Pune',
    },
    decision: {
      id: 'dec-001',
      status: 'deferred',
      decidedAt: '2025-04-20T10:44:00Z',
      decidedBy: 'model',
      riskScore: 0.45,
      cbessScore: 72,
      uncertainty: 0.28,
      confidence: 'medium',
      explanation:
        'Income is moderate but EMI obligations are reasonable. Credit score is average. Recommend human review for final decision.',
      positiveFactors: ['Adequate assets for collateral', 'Stable employment history'],
      negativeFactors: ['Average credit score', 'High debt-to-income ratio'],
      featureImportance: [
        { name: 'EMI', impact: -0.22, value: 8000 },
        { name: 'Income', impact: 0.18, value: 50000 },
        { name: 'Assets', impact: 0.15, value: 1000000 },
      ],
      modelVersion: 'cbes-v2',
    },
    documents: [
      {
        id: 'doc-001',
        fileName: 'bank_statement_april.pdf',
        documentType: 'pdf',
        fileSize: 234003,
        uploadedAt: '2025-04-20T10:35:00Z',
      },
    ],
  },
  {
    id: 'app-uuid-124',
    createdAt: '2025-04-21T09:10:00Z',
    updatedAt: '2025-04-21T09:16:00Z',
    status: 'approved',
    source: 'seed',
    applicantId: 'cust-002',
    applicantName: 'Ananya Shah',
    email: 'ananya.shah@example.com',
    phone: '+91 9988776655',
    loanAmount: 850000,
    loanPurpose: 'home',
    loanTenure: 120,
    applicationData: {
      firstName: 'Ananya',
      lastName: 'Shah',
      gender: 'female',
      education: 'postgraduate',
      monthlyIncome: 125000,
      annualIncome: 1500000,
      emi: 18000,
      existingEmis: 18000,
      employmentType: 'salaried',
      yearsOfEmployment: 9,
      assets: 2400000,
      residentialAssetsValue: 1650000,
      commercialAssetsValue: 250000,
      bankBalance: 500000,
      totalAssets: 2400000,
      liabilities: 200000,
      creditScore: 782,
      creditHistory: 'excellent',
      totalLoans: 6,
      activeLoans: 1,
      closedLoans: 5,
      missedPayments: 0,
      creditUtilizationRatio: 22,
      emiIncomeRatio: 14,
      loanIncomeRatio: 57,
      debtToIncomeRatio: 18,
      age: 31,
      dependents: 1,
      maritalStatus: 'married',
      residenceType: 'rented',
      region: 'west',
      city: 'Mumbai',
    },
    decision: {
      id: 'dec-002',
      status: 'approved',
      decidedAt: '2025-04-21T09:15:00Z',
      decidedBy: 'model',
      riskScore: 0.18,
      cbessScore: 88,
      uncertainty: 0.11,
      confidence: 'high',
      explanation: 'Strong income, low debt burden, and excellent credit profile support approval.',
      positiveFactors: ['High monthly income', 'Low EMI obligations', 'Excellent credit score'],
      negativeFactors: ['Moderate existing liabilities'],
      featureImportance: [
        { name: 'Income', impact: 0.31, value: 125000 },
        { name: 'Credit Score', impact: 0.24, value: 782 },
        { name: 'EMI', impact: -0.08, value: 18000 },
      ],
      modelVersion: 'cbes-v2',
    },
    documents: [],
  },
  {
    id: 'app-uuid-125',
    createdAt: '2025-04-22T08:00:00Z',
    updatedAt: '2025-04-22T08:06:00Z',
    status: 'rejected',
    source: 'seed',
    applicantId: 'cust-003',
    applicantName: 'Vikram Iyer',
    email: 'vikram.iyer@example.com',
    phone: '+91 9123456789',
    loanAmount: 300000,
    loanPurpose: 'personal',
    loanTenure: 36,
    applicationData: {
      firstName: 'Vikram',
      lastName: 'Iyer',
      gender: 'male',
      education: 'graduate',
      monthlyIncome: 28000,
      annualIncome: 336000,
      emi: 14000,
      existingEmis: 14000,
      employmentType: 'business',
      yearsOfEmployment: 2,
      assets: 180000,
      residentialAssetsValue: 90000,
      commercialAssetsValue: 30000,
      bankBalance: 60000,
      totalAssets: 180000,
      liabilities: 240000,
      creditScore: 590,
      creditHistory: 'poor',
      totalLoans: 5,
      activeLoans: 3,
      closedLoans: 2,
      missedPayments: 5,
      creditUtilizationRatio: 79,
      emiIncomeRatio: 50,
      loanIncomeRatio: 89,
      debtToIncomeRatio: 62,
      age: 29,
      dependents: 3,
      maritalStatus: 'married',
      residenceType: 'with_family',
      region: 'south',
      city: 'Chennai',
    },
    decision: {
      id: 'dec-003',
      status: 'rejected',
      decidedAt: '2025-04-22T08:05:00Z',
      decidedBy: 'model',
      riskScore: 0.72,
      cbessScore: 81,
      uncertainty: 0.14,
      confidence: 'high',
      explanation: 'Debt burden is elevated relative to income and credit profile suggests repayment stress.',
      positiveFactors: ['Family-supported residence reduces fixed housing cost'],
      negativeFactors: ['Low credit score', 'High EMI to income ratio', 'Limited asset coverage'],
      featureImportance: [
        { name: 'Credit Score', impact: -0.29, value: 590 },
        { name: 'EMI', impact: -0.24, value: 14000 },
        { name: 'Assets', impact: 0.07, value: 180000 },
      ],
      modelVersion: 'cbes-v2',
    },
    documents: [],
  },
]
